VNG-Realisatie/Haal-Centraal-common

- api-specificatie/common.yaml
> Parameters page en PageSize toegevoegd t.b.v paginering

- features/uri-templating.feature
Naar aanleiding van de feedback van gisteren, heb ik geprobeerd uri templating nog beter te beschrijven.
> Feature: uri templating specs aangepast

- api-specificatie/common.yaml
bij gebruik van required field in response parameter
> Fix: code generatie fout in nSwag

- docs/design_decisions.md
Code van waardelijsten gebruiken in query-parameters.
> Update design decisions n.a.v. #208

- api-specificatie/common.yaml
@strijm Wil jij deze aanpassing in de common.yaml ook checken of deze voldoet aan wat jij verwacht ?
> Toevoegen van enumeratie en default bij contentCRS en acceptCRS

- features/foutafhandeling.feature
zie https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/221
> invalid-params is invalidParams

- api-specificatie/common.yaml
link voorbeeld met https ervoor, pagineringslinks als relatieve link in voorbeeld
>  voorbeelden bij links verbeterd

- api-specificatie/common.yaml
Interne verwijzing + version aangepast
> Herstel aan v1.0.0

- api-specificatie/common.yaml
t.b.v. evolvability naar toekomstige default WGS84
n.a.v. https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/240
> verwijderen default uit crs headers

- api-specificatie/common.yaml
- features/paginering.feature
N.a.v. opmerkingen @strijm, zie #40 (review)
1. Toevoegen last link (laatste pagina) aan feature en common.yaml
2. features/paginering.feature, regel 13: correctie taalfout
3. features/paginering.feature, regel 54 en 76: toevoegen self link
> n.a.v. #46 wijzigingen doorgevoerd

- features/foutafhandeling.feature
n.a.v. https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/263
> toevoegen foutmelding voor array minItems en maxItems

- features/foutafhandeling.feature
> toevoegen foutmelding voor type number

- features/foutafhandeling.feature
n.a.v. https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/264
> toevoegen scenario's voor request header Content-Crs

- features/uri-templating.feature
> afspraak toegevoegd n.a.v. #56

- features/foutafhandeling.feature
> extra foutscenario voor niet ondersteunen combinatie van parameters

- features/fields.feature
beschrijving en scenario voor toepassen fields bij een collectie van resources.
n.a.v. https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/274#issuecomment-656604602
> toevoegen fields i.c.m. collection

- api-specificatie/common.yaml
https://github.com/VNG-Realisatie/Haal-Centraal-BRK-Bevragen/issues/468
> Aanpassing n.a.v. ISSUE 468 uit BRK-bevragen

- docs/design_decisions.md
Alleen DD 5.23 toegevoegd. De rest zijn verschillen met spaties aan het eind van een paragraaf. 
Deze wijziging is inhoudelijk helemaal besproken in #65 maar was niet meer te mergen.
> Design rule voor opnemen foutcodes toegevoegd.

- features/onvolledige_datum.feature
feature onvolledige datum verplaatst vanuit bevragingen ingeschreven personen, omdat deze betrekking heeft op gebruik van de DatumOnvolledig component dit in de common.yaml zit.
> onvolledige datum feature verplaatst van bevraginen-ingeschreven-personen

- features/self-links.feature
feature die beschrijft hoe de self link wordt samengesteld, al dan niet met queryparameters
> feature voor het samenstellen van de self link

- api-specificatie/common.yaml
Deze wijzigingen zijn alleen in de descriptions van datums.
> Wijziging datum omschrijving n.a.v. BRP #677

- features/uri-templating.feature
> feature: meerdere properties verwijzen naar

- features/foutafhandeling.feature
n.a.v. https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/701#issuecomment-705576353 aanpassen title bij foutmelding paramsRequired
> paramsRequired title aangepast

- features/leegwaarden.feature
feature die beschrijft dat leegwaarden niet in het antwoord moeten zitten
> feature leegwaarden

- features/uri-templating.feature
tbv url translatie/mapping in api gateways
> feat: relative url wordt absolute url
